### ISSUE TITLE
face recognition from distance

### ISSUE THREAD

**Issue by gabaynati** [gili123/final_project#2]
OpenCV provides face detection ,however, from a far-off distance(about 10 meters) it doesn't detect well faces.
The game is based on players which play against each other from a fair distance.
OpenCV face detection can be improved to detect from a far-off distance,but it demands more calculation which makes the application to move very slowly, due to the limited resources use of the smartphone.
Therefore we must find a solution which doesn't consume all the smartphone resources.
A solution can be the use of the device's GPS Additionally to the use of OpenCV to reduce calculations.

**Comment by gili123** [comment]
Not relevant anymore!!!
